# -*- coding: utf-8 -*-
"""assignment 2 day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YZAOXAkhp_MObwbCIZQlHBxzW1tJ9sHV
"""

#assignment2 ques1
#delete all occurance of an element from list
mylist = [21, 5, 8, 52, 21, 87]
print("the original list:",mylist)
r_item = 21

#remove the item for all its occurrences
for item in mylist:
	if(item==r_item):
		mylist.remove(r_item)

print("the list after removable item is",mylist)

#Question2
# Python3 program to
# Check if the string is pangram
import string
def pangram(str):
   alphabet = "abcdefghijklmnopqrstuvwxyz"
   for char in alphabet:
      if char not in str.lower():
         return False
   return True
 
string = str(input("enter a string :"))
 
if(pangram(string) == True):
   print("Yes,The string is a pangram")
else:
   print("No,The string is not a pangram")