# -*- coding: utf-8 -*-
"""day3 assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OufqBMr-o0x9lv2f-nhLQ23BgF2F1hkw
"""

#Assignment 3
reciever = [2 , 1 , 5 , 3 , 4]
dict = {
    (reciever_list.index(reciever_list[0])+1):reciever_list[0],
    (reciever_list.index(reciever_list[1])+1):reciever_list[1],
    (reciever_list.index(reciever_list[2])+1):reciever_list[2],
    (reciever_list.index(reciever_list[3])+1):reciever_list[3],
    (reciever_list.index(reciever_list[4])+1):reciever_list[4]
    }
dict
key_list = list(dict.keys())
val_list = list(dict.values())
giver=[0,0,0,0,0]
for i in range(5):
    position = val_list.index(reciever_list[i])
    giver[val_list[position]-1] = key_list[position]
print(giver)

#OTP GENERATION
import  random as r
import string
length = 6
OTP = ' '
charecters = string.ascii_letters + string.digits
for i in range(length):
    OTP = OTP+r.choice(charecters)
print('OTP:',OTP)