# -*- coding: utf-8 -*-
"""Finalproject_merlinemary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rlHl-kl0WksSWoKz_oCDpCRm-vxTVs9W
"""

#project
#celsius to fahrenhiet convertion
celsius = input("enter the celsius value: ")
temp = float(celsius)
(fahrenheit) = (temp * 9/5) + 32
print('fahrenheit:' ,fahrenheit)