# -*- coding: utf-8 -*-
"""S.MERLINEMARY Assignment1 DAY 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iHJrOiyHXka_93OPgaCp6zT0uwmsmWkr
"""

#assignment 1
#sort in descending order
li= input ('Enter the value:').split()
li.sort(reverse=True)
print("the sorted list in descending order:",li)